### ISSUE TITLE
Needs dark-mode option (or clearer CSS classes for overrides) - see workaround

### ISSUE THREAD

**Issue by jasonhargrove** [GokiProtocol/walletkit#109]
We adopted Goki and love it, thank you! A @mithraiclabs (PsyOptions) user (Jerry) requested a dark mode to match our dark-default apps, and we had a few +1s from the team.

Would be great to have official support for this. Will consider opening a PR in the next week (we have a couple things on the wish list).

In the meantime, quick workaround in SCSS:

```scss
[data-reach-dialog-overlay] {
  z-index: 999999;
  .goki-walletkit-modal-wrapper {
    background: black;
    border: 2px solid cyan;
    span, p, h2, div {
      color: white;
    }
    h2 ~ div svg {
      fill: white;
    }
    h2 ~ div div,
    div:nth-of-type(2) div div,
    svg + div {
      background: black;
    }
    button {
      border: 1px solid $cyan;
    }
    a {
      color: $cyan;
    }
  }
}
```
